apiVersion: events.cloud.google.com/v1
kind: CloudPubSubSource
metadata:
  name: cloudpubsubsource-feedback-classified
  labels:
    app: reporting-func
spec:
  topic: feedback-classified
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: reporting-func
