apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trigger-func
  namespace: default
  labels:
    app: trigger-func
spec:
  template:
    metadata:
      labels:
        app: trigger-func
    spec:
      containers:
      - image: gcr.io/sodium-hangar-309319/trigger-func
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/usr/src/app/sglynnbot-key.json"
